function plotAudio(aud, frg)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Apr-2019 17:48:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

t = frg.Start: 1/aud.Fs : frg.End - 1/aud.Fs;
% Create plot
plot(t,aud.Data);

% Create ylabel
ylabel({'Amplitude'});

% Create xlabel
xlabel({'Time (sec.)'});

box(axes1,'on');
